@startuml
!theme plain
skinparam conditionStyle InsideDiamond
|客户端|
/' start '/
(C)
:创建套接字;
:开启一个监听重发次数的线程;
:将客户端socket注册到事件监听列表中;
repeat
    : 阻塞一段时间(200ms)，更新监听列表中的事件;
    while (所有事件处理结束？) is (no)
        partition 消息处理 #lightblue
            : 接受服务端发来的消息;
            if (消息是否为close？) then (yes)
                : 断开连接;
            else (no)
                : 显示消息;
            endif
        }
    end while (yes)
repeat while (客户端关闭?)
: 关闭客户端;
: 释放资源;
stop
@enduml

