@startuml
!theme plain
!include ./design.puml

TCPNode .> NetworkPros
TCPThread .> Message

ServerNode -|> TCPNode
ClientNode --|> TCPNode

ServerThread -|> TCPThread
ClientThread --|> TCPThread

@enduml
