@startuml
!theme plain
skinparam conditionStyle InsideDiamond
|服务端线程|
/' start '/
(S)
:创建soket;
:开始监听;
: 将服务端socket注册到事件监听列表中;
repeat 
    : 阻塞一段时间(500ms)，更新监听列表中的事件;
    while (所有事件处理结束?) is (no)
        if (发生事件的socekt为服务端socket) then (yes)
            partition 处理连接事件 #lightblue
            : 与客户端建立连接;
            : 将连接状态存入状态信息队列中;
            : 将返回的客户端socket注册到事件监听列表中;
        }
        else (no)
            partition 处理消息接收事件 #lightblue
            : 与客户端建立连接;
            : 创建一个新的客户端对象;
            : 接收客户端传来的消息;
            if (消息是否为FIN) then (no)
                : 将接受消息存入接收信息队列中;
                : 向客户端发送响应;
                : 将相应存入状态信息队列中;
            else (yes)
                : 将该客户端socket从注册的事件监听列表中删除;
            endif
        }
        endif
    end while (yes)
repeat while (服务端未关闭)
: 关闭服务端;
: 释放资源;
stop
@enduml

