@startuml
!theme plain
skinparam conditionStyle InsideDiamond
|服务端线程|
/' start '/
(S)
:创建套接字;
:绑定端口;
:开始监听;
: 将服务端socket注册到事件监听列表中;
repeat 
    : 阻塞一段时间(500ms)，更新监听列表中的事件;
    while (所有事件处理结束？) is (no)
        if (服务端套接字事件？) then (yes)
            partition 处理连接事件 #lightblue
            : 接受客户端的连接;
            : 接受客户端的消息（获取名称）;
            : 广播客户端的连接信息;
            : 记录该客户端;
            : 将该客户端注册到事件监听列表中;
        }
        else (no)
            partition 处理消息接收事件 #lightblue
            : 创建一个新的客户端对象;
            : 接收客户端传来的消息;
            : 校验该消息;
            if (是否产生断连异常) then (no)
                : 广播接收到的消息;
            else (yes)
                : 将该客户端从事件监听列表中删除;
            endif
        }
        endif
    end while (yes)
repeat while (服务端未关闭)
: 关闭服务端;
: 释放资源;
stop
@enduml

